let list_data=[
  {
    date:'may 19 2020',
    title:'罗方坤',
    detail_img:'/images/ai.jpg',
    avatar:'/images/ai.jpg',
    detail_content:'你好',
    headImgSrc:'/images/ai.jpg',
    author:'my',
    dataTime:'24time',
    detail_love_image1:'/images/ai.jpg',
    detail_love_image2:'/images/ai.jpg',
    love_count:88,
    attention_count:66,
    detail:'有魅力的老男人',
    music:{
      dataUrl:'http://www.yymp3.com/Play/23182/267127.htm',
      title:'aaa',
      coverImgUrl:'http://p1.music.126.net/3XWznnv38jxpLcxsu5AMvA==/109951164465026826.jpg?param=140y140'
    },
    postId:1
  },
  {
    date:'may 19 2020',
    title:'罗方坤',
    detail_img:'/images/ai.jpg',
    avatar:'/images/ai.jpg',
    detail_content:'你好',
    headImgSrc:'/images/ai.jpg',
    author:'my',
    dataTime:'24time',
    detail_love_image1:'/images/ai.jpg',
    detail_love_image2:'/images/ai.jpg',
    love_count:88,
    attention_count:66,
    detail:'有魅力的老男人',
    music:{
      dataUrl:'http://www.ytmp3.cn/down/50395.mp3',
      coverImgUrl:'http://y.gtimg.cn/music/photo_new/T002R300x300M000003rsKF44Gyask.jpg?max_age=2592000'
    },
    postId:1
  },
  {
    date:'may 19 2020',
    title:'罗方坤',
    detail_img:'/images/ai.jpg',
    avatar:'/images/ai.jpg',
    detail_content:'你好',
    headImgSrc:'/images/ai.jpg',
    author:'my',
    dataTime:'24time',
    detail_love_image1:'/images/ai.jpg',
    detail_love_image2:'/images/ai.jpg',
    love_count:88,
    attention_count:66,
    detail:'有魅力的老男人',
    music:{
      dataUrl:'http://www.ytmp3.cn/down/50395.mp3',
      coverImgUrl:'http://y.gtimg.cn/music/photo_new/T002R300x300M000003rsKF44Gyask.jpg?max_age=2592000'
    },
    postId:1
  },
  {
    date:'may 19 2020',
    title:'罗方坤',
    detail_img:'/images/ai.jpg',
    avatar:'/images/ai.jpg',
    detail_content:'你好',
    headImgSrc:'/images/ai.jpg',
    author:'my',
    dataTime:'24time',
    detail_love_image1:'/images/ai.jpg',
    detail_love_image2:'/images/ai.jpg',
    love_count:88,
    attention_count:66,
    detail:'有魅力的老男人',
    music:{
      dataUrl:'http://www.ytmp3.cn/down/50395.mp3',
      coverImgUrl:'http://y.gtimg.cn/music/photo_new/T002R300x300M000003rsKF44Gyask.jpg?max_age=2592000'
    },
    postId:1
  },
  {
    date:'may 19 2020',
    title:'罗方坤',
    detail_img:'/images/ai.jpg',
    avatar:'/images/ai.jpg',
    detail_content:'你好',
    headImgSrc:'/images/ai.jpg',
    author:'my',
    dataTime:'24time',
    detail_love_image1:'/images/ai.jpg',
    detail_love_image2:'/images/ai.jpg',
    love_count:88,
    attention_count:66,
    detail:'有魅力的老男人',
    music:{
      dataUrl:'http://www.ytmp3.cn/down/50395.mp3',
      coverImgUrl:'http://y.gtimg.cn/music/photo_new/T002R300x300M000003rsKF44Gyask.jpg?max_age=2592000'
    },
    postId:1
  },
  {
    date:'may 19 2020',
    title:'罗方坤',
    detail_img:'/images/ai.jpg',
    avatar:'/images/ai.jpg',
    detail_content:'你好',
    headImgSrc:'/images/ai.jpg',
    author:'my',
    dataTime:'24time',
    detail_love_image1:'/images/ai.jpg',
    detail_love_image2:'/images/ai.jpg',
    love_count:88,
    attention_count:66,
    detail:'有魅力的老男人',
    music:{
      dataUrl:'http://www.ytmp3.cn/down/50395.mp3',
      coverImgUrl:'http://y.gtimg.cn/music/photo_new/T002R300x300M000003rsKF44Gyask.jpg?max_age=2592000'
    },
    postId:1
  },
  {
    date:'may 19 2020',
    title:'罗方坤',
    detail_img:'/images/ai.jpg',
    avatar:'/images/ai.jpg',
    detail_content:'你好',
    headImgSrc:'/images/ai.jpg',
    author:'my',
    dataTime:'24time',
    detail_love_image1:'/images/ai.jpg',
    detail_love_image2:'/images/ai.jpg',
    love_count:88,
    attention_count:66,
    detail:'有魅力的老男人',
    music:{
      dataUrl:'http://www.ytmp3.cn/down/50395.mp3',
      coverImgUrl:'http://y.gtimg.cn/music/photo_new/T002R300x300M000003rsKF44Gyask.jpg?max_age=2592000'
    },
    postId:1
  },
  {
    date:'may 19 2020',
    title:'罗方坤',
    detail_img:'/images/ai.jpg',
    avatar:'/images/ai.jpg',
    detail_content:'你好',
    headImgSrc:'/images/ai.jpg',
    author:'my',
    dataTime:'24time',
    detail_love_image1:'/images/ai.jpg',
    detail_love_image2:'/images/ai.jpg',
    love_count:88,
    attention_count:66,
    detail:'有魅力的老男人',
    music:{
      dataUrl:'http://www.ytmp3.cn/down/50395.mp3',
      coverImgUrl:'http://y.gtimg.cn/music/photo_new/T002R300x300M000003rsKF44Gyask.jpg?max_age=2592000'
    },
    postId:1
  }
  
];

module.exports={list_data};